/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2_gen2_0' in SOPC Builder design 'lab62_soc'
 * SOPC Builder design path: ../../lab62_soc.sopcinfo
 *
 * Generated: Tue Dec 06 22:08:34 CST 2022
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x00001020
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 50000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "tiny"
#define ALT_CPU_DATA_ADDR_WIDTH 0x1c
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x08000020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 50000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 0
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 0
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_ICACHE_SIZE 0
#define ALT_CPU_INST_ADDR_WIDTH 0x1c
#define ALT_CPU_NAME "nios2_gen2_0"
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x08000000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x00001020
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 50000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "tiny"
#define NIOS2_DATA_ADDR_WIDTH 0x1c
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x08000020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 0
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 0
#define NIOS2_ICACHE_LINE_SIZE_LOG2 0
#define NIOS2_ICACHE_SIZE 0
#define NIOS2_INST_ADDR_WIDTH 0x1c
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x08000000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_NEW_SDRAM_CONTROLLER
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_SPI
#define __ALTERA_AVALON_SYSID_QSYS
#define __ALTERA_AVALON_TIMER
#define __ALTERA_NIOS2_GEN2
#define __ALTPLL


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "MAX 10"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart_0"
#define ALT_STDERR_BASE 0x4c8
#define ALT_STDERR_DEV jtag_uart_0
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart_0"
#define ALT_STDIN_BASE 0x4c8
#define ALT_STDIN_DEV jtag_uart_0
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart_0"
#define ALT_STDOUT_BASE 0x4c8
#define ALT_STDOUT_DEV jtag_uart_0
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "lab62_soc"


/*
 * collisionP1 configuration
 *
 */

#define ALT_MODULE_CLASS_collisionP1 altera_avalon_pio
#define COLLISIONP1_BASE 0x380
#define COLLISIONP1_BIT_CLEARING_EDGE_REGISTER 0
#define COLLISIONP1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define COLLISIONP1_CAPTURE 0
#define COLLISIONP1_DATA_WIDTH 1
#define COLLISIONP1_DO_TEST_BENCH_WIRING 0
#define COLLISIONP1_DRIVEN_SIM_VALUE 0
#define COLLISIONP1_EDGE_TYPE "NONE"
#define COLLISIONP1_FREQ 50000000
#define COLLISIONP1_HAS_IN 1
#define COLLISIONP1_HAS_OUT 0
#define COLLISIONP1_HAS_TRI 0
#define COLLISIONP1_IRQ -1
#define COLLISIONP1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define COLLISIONP1_IRQ_TYPE "NONE"
#define COLLISIONP1_NAME "/dev/collisionP1"
#define COLLISIONP1_RESET_VALUE 0
#define COLLISIONP1_SPAN 16
#define COLLISIONP1_TYPE "altera_avalon_pio"


/*
 * collisionP2 configuration
 *
 */

#define ALT_MODULE_CLASS_collisionP2 altera_avalon_pio
#define COLLISIONP2_BASE 0x360
#define COLLISIONP2_BIT_CLEARING_EDGE_REGISTER 0
#define COLLISIONP2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define COLLISIONP2_CAPTURE 0
#define COLLISIONP2_DATA_WIDTH 1
#define COLLISIONP2_DO_TEST_BENCH_WIRING 0
#define COLLISIONP2_DRIVEN_SIM_VALUE 0
#define COLLISIONP2_EDGE_TYPE "NONE"
#define COLLISIONP2_FREQ 50000000
#define COLLISIONP2_HAS_IN 1
#define COLLISIONP2_HAS_OUT 0
#define COLLISIONP2_HAS_TRI 0
#define COLLISIONP2_IRQ -1
#define COLLISIONP2_IRQ_INTERRUPT_CONTROLLER_ID -1
#define COLLISIONP2_IRQ_TYPE "NONE"
#define COLLISIONP2_NAME "/dev/collisionP2"
#define COLLISIONP2_RESET_VALUE 0
#define COLLISIONP2_SPAN 16
#define COLLISIONP2_TYPE "altera_avalon_pio"


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK TIMER_0
#define ALT_TIMESTAMP_CLK none


/*
 * hex_digits_pio configuration
 *
 */

#define ALT_MODULE_CLASS_hex_digits_pio altera_avalon_pio
#define HEX_DIGITS_PIO_BASE 0x450
#define HEX_DIGITS_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define HEX_DIGITS_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define HEX_DIGITS_PIO_CAPTURE 0
#define HEX_DIGITS_PIO_DATA_WIDTH 16
#define HEX_DIGITS_PIO_DO_TEST_BENCH_WIRING 0
#define HEX_DIGITS_PIO_DRIVEN_SIM_VALUE 0
#define HEX_DIGITS_PIO_EDGE_TYPE "NONE"
#define HEX_DIGITS_PIO_FREQ 50000000
#define HEX_DIGITS_PIO_HAS_IN 0
#define HEX_DIGITS_PIO_HAS_OUT 1
#define HEX_DIGITS_PIO_HAS_TRI 0
#define HEX_DIGITS_PIO_IRQ -1
#define HEX_DIGITS_PIO_IRQ_INTERRUPT_CONTROLLER_ID -1
#define HEX_DIGITS_PIO_IRQ_TYPE "NONE"
#define HEX_DIGITS_PIO_NAME "/dev/hex_digits_pio"
#define HEX_DIGITS_PIO_RESET_VALUE 0
#define HEX_DIGITS_PIO_SPAN 16
#define HEX_DIGITS_PIO_TYPE "altera_avalon_pio"


/*
 * jtag_uart_0 configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart_0 altera_avalon_jtag_uart
#define JTAG_UART_0_BASE 0x4c8
#define JTAG_UART_0_IRQ 1
#define JTAG_UART_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_0_NAME "/dev/jtag_uart_0"
#define JTAG_UART_0_READ_DEPTH 64
#define JTAG_UART_0_READ_THRESHOLD 8
#define JTAG_UART_0_SPAN 8
#define JTAG_UART_0_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_0_WRITE_DEPTH 64
#define JTAG_UART_0_WRITE_THRESHOLD 8


/*
 * key configuration
 *
 */

#define ALT_MODULE_CLASS_key altera_avalon_pio
#define KEY_BASE 0x430
#define KEY_BIT_CLEARING_EDGE_REGISTER 0
#define KEY_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KEY_CAPTURE 0
#define KEY_DATA_WIDTH 2
#define KEY_DO_TEST_BENCH_WIRING 0
#define KEY_DRIVEN_SIM_VALUE 0
#define KEY_EDGE_TYPE "NONE"
#define KEY_FREQ 50000000
#define KEY_HAS_IN 1
#define KEY_HAS_OUT 0
#define KEY_HAS_TRI 0
#define KEY_IRQ -1
#define KEY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KEY_IRQ_TYPE "NONE"
#define KEY_NAME "/dev/key"
#define KEY_RESET_VALUE 0
#define KEY_SPAN 16
#define KEY_TYPE "altera_avalon_pio"


/*
 * keycode configuration
 *
 */

#define ALT_MODULE_CLASS_keycode altera_avalon_pio
#define KEYCODE_BASE 0x490
#define KEYCODE_BIT_CLEARING_EDGE_REGISTER 0
#define KEYCODE_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KEYCODE_CAPTURE 0
#define KEYCODE_DATA_WIDTH 8
#define KEYCODE_DO_TEST_BENCH_WIRING 0
#define KEYCODE_DRIVEN_SIM_VALUE 0
#define KEYCODE_EDGE_TYPE "NONE"
#define KEYCODE_FREQ 50000000
#define KEYCODE_HAS_IN 0
#define KEYCODE_HAS_OUT 1
#define KEYCODE_HAS_TRI 0
#define KEYCODE_IRQ -1
#define KEYCODE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KEYCODE_IRQ_TYPE "NONE"
#define KEYCODE_NAME "/dev/keycode"
#define KEYCODE_RESET_VALUE 0
#define KEYCODE_SPAN 16
#define KEYCODE_TYPE "altera_avalon_pio"


/*
 * keycode1 configuration
 *
 */

#define ALT_MODULE_CLASS_keycode1 altera_avalon_pio
#define KEYCODE1_BASE 0x3e0
#define KEYCODE1_BIT_CLEARING_EDGE_REGISTER 0
#define KEYCODE1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KEYCODE1_CAPTURE 0
#define KEYCODE1_DATA_WIDTH 8
#define KEYCODE1_DO_TEST_BENCH_WIRING 0
#define KEYCODE1_DRIVEN_SIM_VALUE 0
#define KEYCODE1_EDGE_TYPE "NONE"
#define KEYCODE1_FREQ 50000000
#define KEYCODE1_HAS_IN 0
#define KEYCODE1_HAS_OUT 1
#define KEYCODE1_HAS_TRI 0
#define KEYCODE1_IRQ -1
#define KEYCODE1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KEYCODE1_IRQ_TYPE "NONE"
#define KEYCODE1_NAME "/dev/keycode1"
#define KEYCODE1_RESET_VALUE 0
#define KEYCODE1_SPAN 16
#define KEYCODE1_TYPE "altera_avalon_pio"


/*
 * keycode2 configuration
 *
 */

#define ALT_MODULE_CLASS_keycode2 altera_avalon_pio
#define KEYCODE2_BASE 0x3f0
#define KEYCODE2_BIT_CLEARING_EDGE_REGISTER 0
#define KEYCODE2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KEYCODE2_CAPTURE 0
#define KEYCODE2_DATA_WIDTH 1
#define KEYCODE2_DO_TEST_BENCH_WIRING 0
#define KEYCODE2_DRIVEN_SIM_VALUE 0
#define KEYCODE2_EDGE_TYPE "NONE"
#define KEYCODE2_FREQ 50000000
#define KEYCODE2_HAS_IN 0
#define KEYCODE2_HAS_OUT 1
#define KEYCODE2_HAS_TRI 0
#define KEYCODE2_IRQ -1
#define KEYCODE2_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KEYCODE2_IRQ_TYPE "NONE"
#define KEYCODE2_NAME "/dev/keycode2"
#define KEYCODE2_RESET_VALUE 0
#define KEYCODE2_SPAN 16
#define KEYCODE2_TYPE "altera_avalon_pio"


/*
 * keycode3 configuration
 *
 */

#define ALT_MODULE_CLASS_keycode3 altera_avalon_pio
#define KEYCODE3_BASE 0x400
#define KEYCODE3_BIT_CLEARING_EDGE_REGISTER 0
#define KEYCODE3_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KEYCODE3_CAPTURE 0
#define KEYCODE3_DATA_WIDTH 1
#define KEYCODE3_DO_TEST_BENCH_WIRING 0
#define KEYCODE3_DRIVEN_SIM_VALUE 0
#define KEYCODE3_EDGE_TYPE "NONE"
#define KEYCODE3_FREQ 50000000
#define KEYCODE3_HAS_IN 0
#define KEYCODE3_HAS_OUT 1
#define KEYCODE3_HAS_TRI 0
#define KEYCODE3_IRQ -1
#define KEYCODE3_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KEYCODE3_IRQ_TYPE "NONE"
#define KEYCODE3_NAME "/dev/keycode3"
#define KEYCODE3_RESET_VALUE 0
#define KEYCODE3_SPAN 16
#define KEYCODE3_TYPE "altera_avalon_pio"


/*
 * keycode4 configuration
 *
 */

#define ALT_MODULE_CLASS_keycode4 altera_avalon_pio
#define KEYCODE4_BASE 0x410
#define KEYCODE4_BIT_CLEARING_EDGE_REGISTER 0
#define KEYCODE4_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KEYCODE4_CAPTURE 0
#define KEYCODE4_DATA_WIDTH 8
#define KEYCODE4_DO_TEST_BENCH_WIRING 0
#define KEYCODE4_DRIVEN_SIM_VALUE 0
#define KEYCODE4_EDGE_TYPE "NONE"
#define KEYCODE4_FREQ 50000000
#define KEYCODE4_HAS_IN 0
#define KEYCODE4_HAS_OUT 1
#define KEYCODE4_HAS_TRI 0
#define KEYCODE4_IRQ -1
#define KEYCODE4_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KEYCODE4_IRQ_TYPE "NONE"
#define KEYCODE4_NAME "/dev/keycode4"
#define KEYCODE4_RESET_VALUE 0
#define KEYCODE4_SPAN 16
#define KEYCODE4_TYPE "altera_avalon_pio"


/*
 * keycode5 configuration
 *
 */

#define ALT_MODULE_CLASS_keycode5 altera_avalon_pio
#define KEYCODE5_BASE 0x3d0
#define KEYCODE5_BIT_CLEARING_EDGE_REGISTER 0
#define KEYCODE5_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KEYCODE5_CAPTURE 0
#define KEYCODE5_DATA_WIDTH 8
#define KEYCODE5_DO_TEST_BENCH_WIRING 0
#define KEYCODE5_DRIVEN_SIM_VALUE 0
#define KEYCODE5_EDGE_TYPE "NONE"
#define KEYCODE5_FREQ 50000000
#define KEYCODE5_HAS_IN 0
#define KEYCODE5_HAS_OUT 1
#define KEYCODE5_HAS_TRI 0
#define KEYCODE5_IRQ -1
#define KEYCODE5_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KEYCODE5_IRQ_TYPE "NONE"
#define KEYCODE5_NAME "/dev/keycode5"
#define KEYCODE5_RESET_VALUE 0
#define KEYCODE5_SPAN 16
#define KEYCODE5_TYPE "altera_avalon_pio"


/*
 * leds_pio configuration
 *
 */

#define ALT_MODULE_CLASS_leds_pio altera_avalon_pio
#define LEDS_PIO_BASE 0x440
#define LEDS_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define LEDS_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LEDS_PIO_CAPTURE 0
#define LEDS_PIO_DATA_WIDTH 14
#define LEDS_PIO_DO_TEST_BENCH_WIRING 0
#define LEDS_PIO_DRIVEN_SIM_VALUE 0
#define LEDS_PIO_EDGE_TYPE "NONE"
#define LEDS_PIO_FREQ 50000000
#define LEDS_PIO_HAS_IN 0
#define LEDS_PIO_HAS_OUT 1
#define LEDS_PIO_HAS_TRI 0
#define LEDS_PIO_IRQ -1
#define LEDS_PIO_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LEDS_PIO_IRQ_TYPE "NONE"
#define LEDS_PIO_NAME "/dev/leds_pio"
#define LEDS_PIO_RESET_VALUE 0
#define LEDS_PIO_SPAN 16
#define LEDS_PIO_TYPE "altera_avalon_pio"


/*
 * marine_enum configuration
 *
 */

#define ALT_MODULE_CLASS_marine_enum altera_avalon_pio
#define MARINE_ENUM_BASE 0x3b0
#define MARINE_ENUM_BIT_CLEARING_EDGE_REGISTER 0
#define MARINE_ENUM_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MARINE_ENUM_CAPTURE 0
#define MARINE_ENUM_DATA_WIDTH 8
#define MARINE_ENUM_DO_TEST_BENCH_WIRING 0
#define MARINE_ENUM_DRIVEN_SIM_VALUE 0
#define MARINE_ENUM_EDGE_TYPE "NONE"
#define MARINE_ENUM_FREQ 50000000
#define MARINE_ENUM_HAS_IN 0
#define MARINE_ENUM_HAS_OUT 1
#define MARINE_ENUM_HAS_TRI 0
#define MARINE_ENUM_IRQ -1
#define MARINE_ENUM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MARINE_ENUM_IRQ_TYPE "NONE"
#define MARINE_ENUM_NAME "/dev/marine_enum"
#define MARINE_ENUM_RESET_VALUE 0
#define MARINE_ENUM_SPAN 16
#define MARINE_ENUM_TYPE "altera_avalon_pio"


/*
 * missile1_x configuration
 *
 */

#define ALT_MODULE_CLASS_missile1_x altera_avalon_pio
#define MISSILE1_X_BASE 0x330
#define MISSILE1_X_BIT_CLEARING_EDGE_REGISTER 0
#define MISSILE1_X_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MISSILE1_X_CAPTURE 0
#define MISSILE1_X_DATA_WIDTH 10
#define MISSILE1_X_DO_TEST_BENCH_WIRING 0
#define MISSILE1_X_DRIVEN_SIM_VALUE 0
#define MISSILE1_X_EDGE_TYPE "NONE"
#define MISSILE1_X_FREQ 50000000
#define MISSILE1_X_HAS_IN 0
#define MISSILE1_X_HAS_OUT 1
#define MISSILE1_X_HAS_TRI 0
#define MISSILE1_X_IRQ -1
#define MISSILE1_X_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MISSILE1_X_IRQ_TYPE "NONE"
#define MISSILE1_X_NAME "/dev/missile1_x"
#define MISSILE1_X_RESET_VALUE 0
#define MISSILE1_X_SPAN 16
#define MISSILE1_X_TYPE "altera_avalon_pio"


/*
 * missile1_y configuration
 *
 */

#define ALT_MODULE_CLASS_missile1_y altera_avalon_pio
#define MISSILE1_Y_BASE 0x320
#define MISSILE1_Y_BIT_CLEARING_EDGE_REGISTER 0
#define MISSILE1_Y_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MISSILE1_Y_CAPTURE 0
#define MISSILE1_Y_DATA_WIDTH 10
#define MISSILE1_Y_DO_TEST_BENCH_WIRING 0
#define MISSILE1_Y_DRIVEN_SIM_VALUE 0
#define MISSILE1_Y_EDGE_TYPE "NONE"
#define MISSILE1_Y_FREQ 50000000
#define MISSILE1_Y_HAS_IN 0
#define MISSILE1_Y_HAS_OUT 1
#define MISSILE1_Y_HAS_TRI 0
#define MISSILE1_Y_IRQ -1
#define MISSILE1_Y_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MISSILE1_Y_IRQ_TYPE "NONE"
#define MISSILE1_Y_NAME "/dev/missile1_y"
#define MISSILE1_Y_RESET_VALUE 0
#define MISSILE1_Y_SPAN 16
#define MISSILE1_Y_TYPE "altera_avalon_pio"


/*
 * missile2_x configuration
 *
 */

#define ALT_MODULE_CLASS_missile2_x altera_avalon_pio
#define MISSILE2_X_BASE 0x310
#define MISSILE2_X_BIT_CLEARING_EDGE_REGISTER 0
#define MISSILE2_X_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MISSILE2_X_CAPTURE 0
#define MISSILE2_X_DATA_WIDTH 10
#define MISSILE2_X_DO_TEST_BENCH_WIRING 0
#define MISSILE2_X_DRIVEN_SIM_VALUE 0
#define MISSILE2_X_EDGE_TYPE "NONE"
#define MISSILE2_X_FREQ 50000000
#define MISSILE2_X_HAS_IN 0
#define MISSILE2_X_HAS_OUT 1
#define MISSILE2_X_HAS_TRI 0
#define MISSILE2_X_IRQ -1
#define MISSILE2_X_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MISSILE2_X_IRQ_TYPE "NONE"
#define MISSILE2_X_NAME "/dev/missile2_x"
#define MISSILE2_X_RESET_VALUE 0
#define MISSILE2_X_SPAN 16
#define MISSILE2_X_TYPE "altera_avalon_pio"


/*
 * missile2_y configuration
 *
 */

#define ALT_MODULE_CLASS_missile2_y altera_avalon_pio
#define MISSILE2_Y_BASE 0x300
#define MISSILE2_Y_BIT_CLEARING_EDGE_REGISTER 0
#define MISSILE2_Y_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MISSILE2_Y_CAPTURE 0
#define MISSILE2_Y_DATA_WIDTH 10
#define MISSILE2_Y_DO_TEST_BENCH_WIRING 0
#define MISSILE2_Y_DRIVEN_SIM_VALUE 0
#define MISSILE2_Y_EDGE_TYPE "NONE"
#define MISSILE2_Y_FREQ 50000000
#define MISSILE2_Y_HAS_IN 0
#define MISSILE2_Y_HAS_OUT 1
#define MISSILE2_Y_HAS_TRI 0
#define MISSILE2_Y_IRQ -1
#define MISSILE2_Y_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MISSILE2_Y_IRQ_TYPE "NONE"
#define MISSILE2_Y_NAME "/dev/missile2_y"
#define MISSILE2_Y_RESET_VALUE 0
#define MISSILE2_Y_SPAN 16
#define MISSILE2_Y_TYPE "altera_avalon_pio"


/*
 * onchip_memory2_0 configuration
 *
 */

#define ALT_MODULE_CLASS_onchip_memory2_0 altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_0_BASE 0x0
#define ONCHIP_MEMORY2_0_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_0_DUAL_PORT 0
#define ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE "lab62_soc_onchip_memory2_0"
#define ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_0_INSTANCE_ID "NONE"
#define ONCHIP_MEMORY2_0_IRQ -1
#define ONCHIP_MEMORY2_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_MEMORY2_0_NAME "/dev/onchip_memory2_0"
#define ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_0_SIZE_VALUE 16
#define ONCHIP_MEMORY2_0_SPAN 16
#define ONCHIP_MEMORY2_0_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_MEMORY2_0_WRITABLE 1


/*
 * p1_hit configuration
 *
 */

#define ALT_MODULE_CLASS_p1_hit altera_avalon_pio
#define P1_HIT_BASE 0x2c0
#define P1_HIT_BIT_CLEARING_EDGE_REGISTER 0
#define P1_HIT_BIT_MODIFYING_OUTPUT_REGISTER 0
#define P1_HIT_CAPTURE 0
#define P1_HIT_DATA_WIDTH 1
#define P1_HIT_DO_TEST_BENCH_WIRING 0
#define P1_HIT_DRIVEN_SIM_VALUE 0
#define P1_HIT_EDGE_TYPE "NONE"
#define P1_HIT_FREQ 50000000
#define P1_HIT_HAS_IN 1
#define P1_HIT_HAS_OUT 0
#define P1_HIT_HAS_TRI 0
#define P1_HIT_IRQ -1
#define P1_HIT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define P1_HIT_IRQ_TYPE "NONE"
#define P1_HIT_NAME "/dev/p1_hit"
#define P1_HIT_RESET_VALUE 0
#define P1_HIT_SPAN 16
#define P1_HIT_TYPE "altera_avalon_pio"


/*
 * p2_hit configuration
 *
 */

#define ALT_MODULE_CLASS_p2_hit altera_avalon_pio
#define P2_HIT_BASE 0x2d0
#define P2_HIT_BIT_CLEARING_EDGE_REGISTER 0
#define P2_HIT_BIT_MODIFYING_OUTPUT_REGISTER 0
#define P2_HIT_CAPTURE 0
#define P2_HIT_DATA_WIDTH 1
#define P2_HIT_DO_TEST_BENCH_WIRING 0
#define P2_HIT_DRIVEN_SIM_VALUE 0
#define P2_HIT_EDGE_TYPE "NONE"
#define P2_HIT_FREQ 50000000
#define P2_HIT_HAS_IN 1
#define P2_HIT_HAS_OUT 0
#define P2_HIT_HAS_TRI 0
#define P2_HIT_IRQ -1
#define P2_HIT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define P2_HIT_IRQ_TYPE "NONE"
#define P2_HIT_NAME "/dev/p2_hit"
#define P2_HIT_RESET_VALUE 0
#define P2_HIT_SPAN 16
#define P2_HIT_TYPE "altera_avalon_pio"


/*
 * player1x configuration
 *
 */

#define ALT_MODULE_CLASS_player1x altera_avalon_pio
#define PLAYER1X_BASE 0x3a0
#define PLAYER1X_BIT_CLEARING_EDGE_REGISTER 0
#define PLAYER1X_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PLAYER1X_CAPTURE 0
#define PLAYER1X_DATA_WIDTH 10
#define PLAYER1X_DO_TEST_BENCH_WIRING 0
#define PLAYER1X_DRIVEN_SIM_VALUE 0
#define PLAYER1X_EDGE_TYPE "NONE"
#define PLAYER1X_FREQ 50000000
#define PLAYER1X_HAS_IN 0
#define PLAYER1X_HAS_OUT 1
#define PLAYER1X_HAS_TRI 0
#define PLAYER1X_IRQ -1
#define PLAYER1X_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PLAYER1X_IRQ_TYPE "NONE"
#define PLAYER1X_NAME "/dev/player1x"
#define PLAYER1X_RESET_VALUE 0
#define PLAYER1X_SPAN 16
#define PLAYER1X_TYPE "altera_avalon_pio"


/*
 * player1y configuration
 *
 */

#define ALT_MODULE_CLASS_player1y altera_avalon_pio
#define PLAYER1Y_BASE 0x390
#define PLAYER1Y_BIT_CLEARING_EDGE_REGISTER 0
#define PLAYER1Y_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PLAYER1Y_CAPTURE 0
#define PLAYER1Y_DATA_WIDTH 10
#define PLAYER1Y_DO_TEST_BENCH_WIRING 0
#define PLAYER1Y_DRIVEN_SIM_VALUE 0
#define PLAYER1Y_EDGE_TYPE "NONE"
#define PLAYER1Y_FREQ 50000000
#define PLAYER1Y_HAS_IN 0
#define PLAYER1Y_HAS_OUT 1
#define PLAYER1Y_HAS_TRI 0
#define PLAYER1Y_IRQ -1
#define PLAYER1Y_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PLAYER1Y_IRQ_TYPE "NONE"
#define PLAYER1Y_NAME "/dev/player1y"
#define PLAYER1Y_RESET_VALUE 0
#define PLAYER1Y_SPAN 16
#define PLAYER1Y_TYPE "altera_avalon_pio"


/*
 * player2x configuration
 *
 */

#define ALT_MODULE_CLASS_player2x altera_avalon_pio
#define PLAYER2X_BASE 0x340
#define PLAYER2X_BIT_CLEARING_EDGE_REGISTER 0
#define PLAYER2X_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PLAYER2X_CAPTURE 0
#define PLAYER2X_DATA_WIDTH 10
#define PLAYER2X_DO_TEST_BENCH_WIRING 0
#define PLAYER2X_DRIVEN_SIM_VALUE 0
#define PLAYER2X_EDGE_TYPE "NONE"
#define PLAYER2X_FREQ 50000000
#define PLAYER2X_HAS_IN 0
#define PLAYER2X_HAS_OUT 1
#define PLAYER2X_HAS_TRI 0
#define PLAYER2X_IRQ -1
#define PLAYER2X_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PLAYER2X_IRQ_TYPE "NONE"
#define PLAYER2X_NAME "/dev/player2x"
#define PLAYER2X_RESET_VALUE 0
#define PLAYER2X_SPAN 16
#define PLAYER2X_TYPE "altera_avalon_pio"


/*
 * player2y configuration
 *
 */

#define ALT_MODULE_CLASS_player2y altera_avalon_pio
#define PLAYER2Y_BASE 0x350
#define PLAYER2Y_BIT_CLEARING_EDGE_REGISTER 0
#define PLAYER2Y_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PLAYER2Y_CAPTURE 0
#define PLAYER2Y_DATA_WIDTH 10
#define PLAYER2Y_DO_TEST_BENCH_WIRING 0
#define PLAYER2Y_DRIVEN_SIM_VALUE 0
#define PLAYER2Y_EDGE_TYPE "NONE"
#define PLAYER2Y_FREQ 50000000
#define PLAYER2Y_HAS_IN 0
#define PLAYER2Y_HAS_OUT 1
#define PLAYER2Y_HAS_TRI 0
#define PLAYER2Y_IRQ -1
#define PLAYER2Y_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PLAYER2Y_IRQ_TYPE "NONE"
#define PLAYER2Y_NAME "/dev/player2y"
#define PLAYER2Y_RESET_VALUE 0
#define PLAYER2Y_SPAN 16
#define PLAYER2Y_TYPE "altera_avalon_pio"


/*
 * scorep1 configuration
 *
 */

#define ALT_MODULE_CLASS_scorep1 altera_avalon_pio
#define SCOREP1_BASE 0x2e0
#define SCOREP1_BIT_CLEARING_EDGE_REGISTER 0
#define SCOREP1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SCOREP1_CAPTURE 0
#define SCOREP1_DATA_WIDTH 8
#define SCOREP1_DO_TEST_BENCH_WIRING 0
#define SCOREP1_DRIVEN_SIM_VALUE 0
#define SCOREP1_EDGE_TYPE "NONE"
#define SCOREP1_FREQ 50000000
#define SCOREP1_HAS_IN 0
#define SCOREP1_HAS_OUT 1
#define SCOREP1_HAS_TRI 0
#define SCOREP1_IRQ -1
#define SCOREP1_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SCOREP1_IRQ_TYPE "NONE"
#define SCOREP1_NAME "/dev/scorep1"
#define SCOREP1_RESET_VALUE 0
#define SCOREP1_SPAN 16
#define SCOREP1_TYPE "altera_avalon_pio"


/*
 * scorep2 configuration
 *
 */

#define ALT_MODULE_CLASS_scorep2 altera_avalon_pio
#define SCOREP2_BASE 0x2f0
#define SCOREP2_BIT_CLEARING_EDGE_REGISTER 0
#define SCOREP2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SCOREP2_CAPTURE 0
#define SCOREP2_DATA_WIDTH 8
#define SCOREP2_DO_TEST_BENCH_WIRING 0
#define SCOREP2_DRIVEN_SIM_VALUE 0
#define SCOREP2_EDGE_TYPE "NONE"
#define SCOREP2_FREQ 50000000
#define SCOREP2_HAS_IN 0
#define SCOREP2_HAS_OUT 1
#define SCOREP2_HAS_TRI 0
#define SCOREP2_IRQ -1
#define SCOREP2_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SCOREP2_IRQ_TYPE "NONE"
#define SCOREP2_NAME "/dev/scorep2"
#define SCOREP2_RESET_VALUE 0
#define SCOREP2_SPAN 16
#define SCOREP2_TYPE "altera_avalon_pio"


/*
 * sdram configuration
 *
 */

#define ALT_MODULE_CLASS_sdram altera_avalon_new_sdram_controller
#define SDRAM_BASE 0x8000000
#define SDRAM_CAS_LATENCY 3
#define SDRAM_CONTENTS_INFO
#define SDRAM_INIT_NOP_DELAY 0.0
#define SDRAM_INIT_REFRESH_COMMANDS 2
#define SDRAM_IRQ -1
#define SDRAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SDRAM_IS_INITIALIZED 1
#define SDRAM_NAME "/dev/sdram"
#define SDRAM_POWERUP_DELAY 200.0
#define SDRAM_REFRESH_PERIOD 15.625
#define SDRAM_REGISTER_DATA_IN 1
#define SDRAM_SDRAM_ADDR_WIDTH 0x19
#define SDRAM_SDRAM_BANK_WIDTH 2
#define SDRAM_SDRAM_COL_WIDTH 10
#define SDRAM_SDRAM_DATA_WIDTH 16
#define SDRAM_SDRAM_NUM_BANKS 4
#define SDRAM_SDRAM_NUM_CHIPSELECTS 1
#define SDRAM_SDRAM_ROW_WIDTH 13
#define SDRAM_SHARED_DATA 0
#define SDRAM_SIM_MODEL_BASE 0
#define SDRAM_SPAN 67108864
#define SDRAM_STARVATION_INDICATOR 0
#define SDRAM_TRISTATE_BRIDGE_SLAVE ""
#define SDRAM_TYPE "altera_avalon_new_sdram_controller"
#define SDRAM_T_AC 5.4
#define SDRAM_T_MRD 3
#define SDRAM_T_RCD 20.0
#define SDRAM_T_RFC 70.0
#define SDRAM_T_RP 20.0
#define SDRAM_T_WR 14.0


/*
 * sdram_pll configuration
 *
 */

#define ALT_MODULE_CLASS_sdram_pll altpll
#define SDRAM_PLL_BASE 0x4a0
#define SDRAM_PLL_IRQ -1
#define SDRAM_PLL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SDRAM_PLL_NAME "/dev/sdram_pll"
#define SDRAM_PLL_SPAN 16
#define SDRAM_PLL_TYPE "altpll"


/*
 * spi_0 configuration
 *
 */

#define ALT_MODULE_CLASS_spi_0 altera_avalon_spi
#define SPI_0_BASE 0xc0
#define SPI_0_CLOCKMULT 1
#define SPI_0_CLOCKPHASE 0
#define SPI_0_CLOCKPOLARITY 0
#define SPI_0_CLOCKUNITS "Hz"
#define SPI_0_DATABITS 8
#define SPI_0_DATAWIDTH 16
#define SPI_0_DELAYMULT "1.0E-9"
#define SPI_0_DELAYUNITS "ns"
#define SPI_0_EXTRADELAY 0
#define SPI_0_INSERT_SYNC 0
#define SPI_0_IRQ 3
#define SPI_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SPI_0_ISMASTER 1
#define SPI_0_LSBFIRST 0
#define SPI_0_NAME "/dev/spi_0"
#define SPI_0_NUMSLAVES 1
#define SPI_0_PREFIX "spi_"
#define SPI_0_SPAN 32
#define SPI_0_SYNC_REG_DEPTH 2
#define SPI_0_TARGETCLOCK 2500000u
#define SPI_0_TARGETSSDELAY "0.0"
#define SPI_0_TYPE "altera_avalon_spi"


/*
 * sprite2_animation configuration
 *
 */

#define ALT_MODULE_CLASS_sprite2_animation altera_avalon_pio
#define SPRITE2_ANIMATION_BASE 0x370
#define SPRITE2_ANIMATION_BIT_CLEARING_EDGE_REGISTER 0
#define SPRITE2_ANIMATION_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SPRITE2_ANIMATION_CAPTURE 0
#define SPRITE2_ANIMATION_DATA_WIDTH 3
#define SPRITE2_ANIMATION_DO_TEST_BENCH_WIRING 0
#define SPRITE2_ANIMATION_DRIVEN_SIM_VALUE 0
#define SPRITE2_ANIMATION_EDGE_TYPE "NONE"
#define SPRITE2_ANIMATION_FREQ 50000000
#define SPRITE2_ANIMATION_HAS_IN 0
#define SPRITE2_ANIMATION_HAS_OUT 1
#define SPRITE2_ANIMATION_HAS_TRI 0
#define SPRITE2_ANIMATION_IRQ -1
#define SPRITE2_ANIMATION_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SPRITE2_ANIMATION_IRQ_TYPE "NONE"
#define SPRITE2_ANIMATION_NAME "/dev/sprite2_animation"
#define SPRITE2_ANIMATION_RESET_VALUE 0
#define SPRITE2_ANIMATION_SPAN 16
#define SPRITE2_ANIMATION_TYPE "altera_avalon_pio"


/*
 * sprite_enum configuration
 *
 */

#define ALT_MODULE_CLASS_sprite_enum altera_avalon_pio
#define SPRITE_ENUM_BASE 0x420
#define SPRITE_ENUM_BIT_CLEARING_EDGE_REGISTER 0
#define SPRITE_ENUM_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SPRITE_ENUM_CAPTURE 0
#define SPRITE_ENUM_DATA_WIDTH 8
#define SPRITE_ENUM_DO_TEST_BENCH_WIRING 0
#define SPRITE_ENUM_DRIVEN_SIM_VALUE 0
#define SPRITE_ENUM_EDGE_TYPE "NONE"
#define SPRITE_ENUM_FREQ 50000000
#define SPRITE_ENUM_HAS_IN 0
#define SPRITE_ENUM_HAS_OUT 1
#define SPRITE_ENUM_HAS_TRI 0
#define SPRITE_ENUM_IRQ -1
#define SPRITE_ENUM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SPRITE_ENUM_IRQ_TYPE "NONE"
#define SPRITE_ENUM_NAME "/dev/sprite_enum"
#define SPRITE_ENUM_RESET_VALUE 0
#define SPRITE_ENUM_SPAN 16
#define SPRITE_ENUM_TYPE "altera_avalon_pio"


/*
 * sprite_enum2 configuration
 *
 */

#define ALT_MODULE_CLASS_sprite_enum2 altera_avalon_pio
#define SPRITE_ENUM2_BASE 0x3c0
#define SPRITE_ENUM2_BIT_CLEARING_EDGE_REGISTER 0
#define SPRITE_ENUM2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SPRITE_ENUM2_CAPTURE 0
#define SPRITE_ENUM2_DATA_WIDTH 8
#define SPRITE_ENUM2_DO_TEST_BENCH_WIRING 0
#define SPRITE_ENUM2_DRIVEN_SIM_VALUE 0
#define SPRITE_ENUM2_EDGE_TYPE "NONE"
#define SPRITE_ENUM2_FREQ 50000000
#define SPRITE_ENUM2_HAS_IN 0
#define SPRITE_ENUM2_HAS_OUT 1
#define SPRITE_ENUM2_HAS_TRI 0
#define SPRITE_ENUM2_IRQ -1
#define SPRITE_ENUM2_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SPRITE_ENUM2_IRQ_TYPE "NONE"
#define SPRITE_ENUM2_NAME "/dev/sprite_enum2"
#define SPRITE_ENUM2_RESET_VALUE 0
#define SPRITE_ENUM2_SPAN 16
#define SPRITE_ENUM2_TYPE "altera_avalon_pio"


/*
 * sysid_qsys_0 configuration
 *
 */

#define ALT_MODULE_CLASS_sysid_qsys_0 altera_avalon_sysid_qsys
#define SYSID_QSYS_0_BASE 0x4c0
#define SYSID_QSYS_0_ID 0
#define SYSID_QSYS_0_IRQ -1
#define SYSID_QSYS_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYSID_QSYS_0_NAME "/dev/sysid_qsys_0"
#define SYSID_QSYS_0_SPAN 8
#define SYSID_QSYS_0_TIMESTAMP 1670385829
#define SYSID_QSYS_0_TYPE "altera_avalon_sysid_qsys"


/*
 * timer_0 configuration
 *
 */

#define ALT_MODULE_CLASS_timer_0 altera_avalon_timer
#define TIMER_0_ALWAYS_RUN 0
#define TIMER_0_BASE 0x80
#define TIMER_0_COUNTER_SIZE 64
#define TIMER_0_FIXED_PERIOD 0
#define TIMER_0_FREQ 50000000
#define TIMER_0_IRQ 2
#define TIMER_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMER_0_LOAD_VALUE 49999
#define TIMER_0_MULT 0.001
#define TIMER_0_NAME "/dev/timer_0"
#define TIMER_0_PERIOD 1
#define TIMER_0_PERIOD_UNITS "ms"
#define TIMER_0_RESET_OUTPUT 0
#define TIMER_0_SNAPSHOT 1
#define TIMER_0_SPAN 64
#define TIMER_0_TICKS_PER_SEC 1000
#define TIMER_0_TIMEOUT_PULSE_OUTPUT 0
#define TIMER_0_TYPE "altera_avalon_timer"


/*
 * usb_gpx configuration
 *
 */

#define ALT_MODULE_CLASS_usb_gpx altera_avalon_pio
#define USB_GPX_BASE 0x470
#define USB_GPX_BIT_CLEARING_EDGE_REGISTER 0
#define USB_GPX_BIT_MODIFYING_OUTPUT_REGISTER 0
#define USB_GPX_CAPTURE 0
#define USB_GPX_DATA_WIDTH 1
#define USB_GPX_DO_TEST_BENCH_WIRING 0
#define USB_GPX_DRIVEN_SIM_VALUE 0
#define USB_GPX_EDGE_TYPE "NONE"
#define USB_GPX_FREQ 50000000
#define USB_GPX_HAS_IN 1
#define USB_GPX_HAS_OUT 0
#define USB_GPX_HAS_TRI 0
#define USB_GPX_IRQ -1
#define USB_GPX_IRQ_INTERRUPT_CONTROLLER_ID -1
#define USB_GPX_IRQ_TYPE "NONE"
#define USB_GPX_NAME "/dev/usb_gpx"
#define USB_GPX_RESET_VALUE 0
#define USB_GPX_SPAN 16
#define USB_GPX_TYPE "altera_avalon_pio"


/*
 * usb_irq configuration
 *
 */

#define ALT_MODULE_CLASS_usb_irq altera_avalon_pio
#define USB_IRQ_BASE 0x480
#define USB_IRQ_BIT_CLEARING_EDGE_REGISTER 0
#define USB_IRQ_BIT_MODIFYING_OUTPUT_REGISTER 0
#define USB_IRQ_CAPTURE 0
#define USB_IRQ_DATA_WIDTH 1
#define USB_IRQ_DO_TEST_BENCH_WIRING 0
#define USB_IRQ_DRIVEN_SIM_VALUE 0
#define USB_IRQ_EDGE_TYPE "NONE"
#define USB_IRQ_FREQ 50000000
#define USB_IRQ_HAS_IN 1
#define USB_IRQ_HAS_OUT 0
#define USB_IRQ_HAS_TRI 0
#define USB_IRQ_IRQ -1
#define USB_IRQ_IRQ_INTERRUPT_CONTROLLER_ID -1
#define USB_IRQ_IRQ_TYPE "NONE"
#define USB_IRQ_NAME "/dev/usb_irq"
#define USB_IRQ_RESET_VALUE 0
#define USB_IRQ_SPAN 16
#define USB_IRQ_TYPE "altera_avalon_pio"


/*
 * usb_rst configuration
 *
 */

#define ALT_MODULE_CLASS_usb_rst altera_avalon_pio
#define USB_RST_BASE 0x460
#define USB_RST_BIT_CLEARING_EDGE_REGISTER 0
#define USB_RST_BIT_MODIFYING_OUTPUT_REGISTER 0
#define USB_RST_CAPTURE 0
#define USB_RST_DATA_WIDTH 1
#define USB_RST_DO_TEST_BENCH_WIRING 0
#define USB_RST_DRIVEN_SIM_VALUE 0
#define USB_RST_EDGE_TYPE "NONE"
#define USB_RST_FREQ 50000000
#define USB_RST_HAS_IN 0
#define USB_RST_HAS_OUT 1
#define USB_RST_HAS_TRI 0
#define USB_RST_IRQ -1
#define USB_RST_IRQ_INTERRUPT_CONTROLLER_ID -1
#define USB_RST_IRQ_TYPE "NONE"
#define USB_RST_NAME "/dev/usb_rst"
#define USB_RST_RESET_VALUE 0
#define USB_RST_SPAN 16
#define USB_RST_TYPE "altera_avalon_pio"

#endif /* __SYSTEM_H_ */
